# Version attribute removed (obsolete)
services: # Les services que nous allons utiliser
    mysql: # Services mysql
      image: mysql:8.0 # Image mysql version 8.0
      container_name: taskmanager-mysql # Nom du container
      environment: # Variables d'environnement
        MYSQL_ROOT_PASSWORD: rootpassword # Mot de passe root
        MYSQL_DATABASE: taskmanager # Nom de la base de données
        MYSQL_USER: user # Nom d'utilisateur
        MYSQL_PASSWORD: password # Mot de passe
      ports:
        - "3306:3306" # Port de connexion
      volumes:
        # --- Correction ici : Syntaxe Bind Mount ---
        # Spécifie explicitement le type 'bind'
        # 'source' est le chemin ABSOLU sur VOTRE PC (l'hôte)
        # 'target' est le chemin A L'INTERIEUR du conteneur MySQL
        - type: bind
          # Utiliser des slashes '/' est souvent plus compatible avec Docker Compose même sous Windows
          source: C:/Users/arbad/OneDrive - STUDI/Documents/mysql-data
          target: /var/lib/mysql

    phpmyadmin: # Serviice phpMyAdmin
      image: phpmyadmin/phpmyadmin # Image phpMyAdmin
      container_name: taskmannager-phpmyadmin # Nom du container
      environment: # Variables d'environnement
        PMA_HOST: mysql # Nom de l'hôte
        PMA_PORT: 3306 # Port de connexion
      ports: # Port de connexion
        - "8080:80"
      depends_on: # Dépendance
        - mysql

# --- Section 'volumes:' du bas SUPPRIMÉE ---
# car nous utilisons un bind mount ci-dessus, pas un volume nommé géré par Docker.
# volumes:
#  mysql-data: