# Utilisation d'une image de base Node.js
FROM node:18

# Création du répertoire de travaildans le conqteneur
WORKDIR /app

# Copie des fichiers du pri=ojet dans le conteneur
COPY package*.json ./

# Installation des dépendances
RUN npm install

# Copie du reste des fichiers dans le conteneur
COPY . .

# Exposition du port utilisé par l'application
EXPOSE 8080

# Commande pour démarrer l'application
CMD ["npm", "start"]